import { jsPDF } from 'jspdf';

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      return successful;
    }
  } catch (err) {
    console.error('Failed to copy text: ', err);
    return false;
  }
}

export function downloadAsFile(filename: string, content: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadAsMarkdown(title: string, content: string) {
  const cleanTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 40) || 'nexora-note';
  const mdContent = `# ${title}\n\n*Generated by Nexora on ${new Date().toLocaleDateString()}*\n\n---\n\n${content}`;
  downloadAsFile(`${cleanTitle}.md`, mdContent, 'text/markdown;charset=utf-8');
}

export function downloadAsPlainText(title: string, content: string) {
  const cleanTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 40) || 'nexora-note';
  downloadAsFile(`${cleanTitle}.txt`, content, 'text/plain;charset=utf-8');
}

export function downloadAsPDF(title: string, content: string) {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const cleanTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 40) || 'nexora-document';

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(30, 41, 59);
    doc.text(title, 20, 22);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by Nexora  |  ${new Date().toLocaleDateString()}`, 20, 29);

    doc.setDrawColor(226, 232, 240);
    doc.line(20, 33, 190, 33);

    // Body text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);

    // Strip rough markdown tags for clean PDF rendering
    const plainFormatted = content
      .replace(/^#{1,6}\s+(.*)$/gm, '\n$1\n')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/```[a-z]*\n([\s\S]*?)```/g, '\n[Code Block]\n$1\n')
      .replace(/`([^`]+)`/g, '$1');

    const splitText = doc.splitTextToSize(plainFormatted, 170);

    let cursorY = 42;
    const pageHeight = doc.internal.pageSize.height;

    for (let i = 0; i < splitText.length; i++) {
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        cursorY = 20;
      }
      doc.text(splitText[i], 20, cursorY);
      cursorY += 6;
    }

    doc.save(`${cleanTitle}.pdf`);
  } catch (e) {
    console.error('PDF export error, falling back to markdown download:', e);
    downloadAsMarkdown(title, content);
  }
}
